# Análise dos dados

## Importando bibliotecas

In [1]:
import pandas as pd
import re

## Carregando e visualizando os dados

In [2]:
df = pd.read_csv("dados_ficha_a_desafio.csv")

In [3]:
df.iloc[0:10, 0:20]

,id_paciente,sexo,obito,bairro,raca_cor,ocupacao,religiao,luz_eletrica,data_cadastro,escolaridade,nacionalidade,renda_familiar,data_nascimento,em_situacao_de_rua,frequenta_escola,meios_transporte,doencas_condicoes,identidade_genero,meios_comunicacao,orientacao_sexual
0,cd6daa6e-038d-4952-af29-579e62e07f97,male,0,Parada de Lucas,Branca,Não se aplica,Sem religião,True,2021-06-24 00:00:00.000,Fundamental Incompleto,Brasileira,2 Salários Mínimos,1996-06-25,0,0,Ônibus,"[""Outros""]",Cis,"Internet, Televisão",Heterossexual
1,ad6cecb2-3a44-49ab-b2f3-6f9ffc2e2ec7,male,0,Cidade Nova,Parda,Assistente Administrativo,Evangélica,1,2021-01-07 00:00:00.000,Médio Incompleto,Brasileira,1 Salário Mínimo,1952-12-20,0,0,Ônibus,Hipertensão,Não,"Internet, Televisão",Heterossexual
2,54e834e7-e722-4daa-8909-cf917a1247e6,male,0,Santa cruz,Parda,Não se aplica,Católica,1,2021-02-18 00:00:00.000,Fundamental Completo,Brasileira,1 Salário Mínimo,1931-11-14,0,0,"Carro, Metrô, Ônibus, Trem",[],Não,[],Heterossexual
3,c6a71e5e-0933-48d1-9d5a-8f448dc37f71,female,False,Bangu,Branca,Representante Comercial Autônomo,Sem religião,1,2022-03-09 10:40:37,Alfabetizado,Brasileira,1/2 Salário Mínimo,1988-12-06,0,0,"Carro, Ônibus","[""Outros""]",Não,"[""R\u00e1dio"", ""Televis\u00e3o"", ""Jornal"", ""In...",Heterossexual
4,d5262a3c-e5d3-4195-a46b-0acd2533e1d6,male,0,Santíssimo,Branca,Técnico Eletricista,Outra,True,2022-12-13 18:30:45,Médio Completo,Brasileira,1 Salário Mínimo,1971-01-26,0,1,"Metrô, Ônibus",[],Não,"[""Televis\u00e3o"", ""Internet"", ""Jornal""]",Heterossexual
5,4cc6a63c-61d3-49c0-807c-089c3d960956,female,0,Jardim Vinte e Cinco de Agosto,Parda,Porteiro de Edifícios,Católica,True,2021-05-13 00:00:00.000,Fundamental Incompleto,Brasileira,1 Salário Mínimo,1983-12-28,0,0,"[""Carro""]","Diabetes, Hipertensão",Não,Televisão,Heterossexual
6,845241a6-be84-4c77-ae3a-751da1f9d434,male,0,Penha Circular,Parda,Não se aplica,Sem religião,1,2021-05-19 13:47:06.500,Médio Completo,Brasileira,1/2 Salário Mínimo,1998-02-17,0,0,"Alternativo, Carro, Metrô, Ônibus, Outros, Trem","[""Diabetes""]",Não,"Internet, Televisão",Heterossexual
7,bc094be5-82fa-42b5-a22e-fa7ec64cb1fb,female,0,Guadalupe,Parda,Não se aplica,Sem religião,1,2021-08-02 16:16:51.490,Fundamental Completo,Brasileira,1 Salário Mínimo,2011-07-16,0,0,[],Diabetes,Não,"Rádio, Televisão",Heterossexual
8,ab4595b2-c3de-4993-91f5-dfabd8202e12,male,0,Manguinhos,Parda,Motorista de Táxi,Evangélica,0,2021-10-06 00:00:00.000,Fundamental Incompleto,Brasileira,1/2 Salário Mínimo,1993-10-30,0,0,"Carro, Ônibus",[],Outro,"[""Televis\u00e3o"", ""Internet""]",Heterossexual
9,cc2c75b0-4a49-4a22-9ac0-071e05e90411,male,0,Irajá,Parda,Não se aplica,Outra,1,2022-12-20 07:16:32.703,Médio Incompleto,Brasileira,2 Salários Mínimos,1997-09-14,0,0,"Metrô, Ônibus, Trem",[],Cis,Internet,Heterossexual

In [4]:
df.iloc[0:10, 20:35]

,possui_plano_saude,em_caso_doenca_procura,situacao_profissional,vulnerabilidade_social,data_atualizacao_cadastro,familia_beneficiaria_auxilio_brasil,crianca_matriculada_creche_pre_escola,altura,peso,pressao_sistolica,pressao_diastolica,n_atendimentos_atencao_primaria,n_atendimentos_hospital,updated_at,tipo
0,False,Hospital Público,Emprego Formal,0,2022-07-08 22:45:09.710,0,0,172.0,52.5,110.0,70.0,8,9,2021-06-01 00:00:00.000,historico
1,1,[],Autônomo com previdência social,0,2022-07-10 17:48:09.600,1,0,158.0,76.2,140.0,80.0,0,6,2020-06-25 00:00:00.000,historico
2,0,"Hospital Público, Unidade de Saúde",Emprego Formal,0,2023-05-06 09:19:33,0,0,53.0,82.5,180.0,60.0,5,2,2020-03-02 00:00:00.000,historico
3,0,Hospital Público,Não se aplica,0,2022-03-15 09:35:04.550,1,1,164.0,90.6,120.0,70.0,0,27,2021-11-05 11:08:17.477,rotineiro
4,0,[],Não trabalha,0,2022-07-03 22:52:09,0,0,154.0,8.5,180.0,80.0,25,0,2020-11-11 00:00:00.000,historico
5,False,"Hospital Público, Unidade de Saúde",Desempregado,0,2024-06-11 12:06:35.763,False,0,170.0,78.4,120.0,80.0,7,0,2024-08-15 18:51:00.120,historico
6,0,"Hospital Público, Rede Privada, Unidade de Saúde",Não se aplica,0,2023-03-13 14:38:06.843,0,1,155.0,60.0,140.0,70.0,0,6,1900-01-01 00:00:00.000,historico
7,0,Hospital Público,Não se aplica,0,2023-03-08 16:08:31.497,False,0,54.5,64.0,120.0,90.0,10,0,2020-09-02 00:00:00.000,historico
8,0,Hospital Público,Emprego Formal,0,2023-09-29 09:05:44,0,False,63.0,64.0,110.0,80.0,2,50,2024-11-06 10:54:20,historico
9,0,"[""Hospital P\u00fablico"", ""Unidade de Sa\u00fa...",Desempregado,0,2022-09-20 14:22:21.130,True,1,60.0,93.1,150.0,60.0,5,12,2020-09-04 00:00:00.000,historico

## Problemas

Os problemas foram observados a partir de uma observação dos dados e como eles foram identificados na BigQuery. Temos 35 colunas, com seus nomes, tipos (identificados automaticamente na BigQuery) e descrições especificados abaixo:

|  Coluna  |  Tipo  |  Descrição  |
|----------|--------|-------------|
|  id_paciente  |  STRING  |  Identificador de paciente  |
|  sexo  |  STRING  |  Sexo  |
|  obito  |  STRING  |  Indicação de óbito  |
|  bairro  |  STRING  |  Nome do bairro  |
|  raca_cor  |  STRING  |  Descrição de raça/cor  |
|  ocupacao  |  STRING  |  Ocupação exercida  |
|  religiao  |  STRING  |  Religião exercida  |
|  luz_eletrica  |  STRING  |  Indicação se possui luz elétrica  |
|  data_cadastro  |  TIMESTAMP  |  Data de cadastro do paciente  |
|  escolaridade  |  STRING  |  Nível de escolaridade  |
|  nacionalidade  |  STRING  |  Nacionalidade  |
|  renda_familiar  |  STRING  |  Renda familiar  |
|  data_nascimento  |  DATE  |  Data de nascimento  |
|  em_situacao_de_rua  |  STRING  |  Indicação se em situação de rua  |
|  frequenta_escola  |  INTEGER  |  Indicação se frequenta escola  |
|  meios_transporte  |  STRING  |  Meios de transporte utilizados  |
|  doencas_condicoes  |  STRING  |  Doenças ou condições de saúde  |
|  identidade_genero  |  STRING  |  Identidade de gênero  |
|  meios_comunicacao  |  STRING  |  Meios de comunicação utilizados  |
|  orientacao_sexual  |  STRING  |  Orientação sexual  |
|  possui_plano_saude  |  STRING  |  Indicação se possui plano de saúde  |
|  em_caso_doenca_procura  |  STRING  |  Indicação sobre a quem procura em caso de doença  |
|  situacao_profissional  |  STRING  |  Situação profissional  |
|  vulnerabilidade_social  |  STRING  |  Vulnerabilidades sociais  |
|  data_atualizacao_cadastro  |  TIMESTAMP  |  Data da última atualização cadastral do paciente  |
|  familia_beneficiaria_auxilio_brasil  |  STRING  |  Indicação se a família do paciente é beneficiária  |
|  crianca_matriculada_creche_pre_escola  |  STRING  |  Indicação se a criança está matriculada em creche ou pré-escola  |
|  altura  |  FLOAT  |  Altura medida  |
|  peso  |  FLOAT  |  Peso medido  |
|  pressao_sistolica  |  FLOAT  |  Pressão sistólica medida  |
|  pressao_diastolica  |  FLOAT  |  Pressão diastólica medida  |
|  n_atendimentos_atencao_primaria  |  INTEGER  |  Quantidade de atendimentos na atenção primária no último ano  |
|  n_atendimentos_hospital  |  INTEGER  |  Quantidade de atendimentos no hospital no último ano  |
|  updated_at  |  TIMESTAMP  |  Data e hora da última atualização dos dados  |
|  tipo  |  STRING  |  Identifica se dado veio de fluxo rotineiro ou histórico  |

### 1. Valores (str) que deveriam ser booleanos

Os problemas percebidos logo de cara são a maioria das colunas, que são strings, apesar de que há muitas colunas binárias que deveriam ser consideradas booleanos, pois indicam verdadeiro ou falso, sendo elas `obito`, `luz_eletrica`, `em_situacao_de_rua`, `possui_plano_saude` e `familia_beneficiaria_auxilio_brasil`, elas tem os valores `0`, `1`, `TRUE`, `FALSE`, então deve ser padronizado e transformado em booleano.

In [5]:
print(df['obito'].unique())
print(df['luz_eletrica'].unique())
print(df['em_situacao_de_rua'].unique())
print(df['possui_plano_saude'].unique())
print(df['familia_beneficiaria_auxilio_brasil'].unique())

['0' 'False' '1' 'True']
['True' '1' '0' 'False']
['0' 'False' '1']
['False' '1' '0' 'True']
['0' '1' 'False' 'True']

### 2. Valores (int) que deveriam ser booleanos
Também há a coluna `frequenta_escola`, que está como inteira mas os valores são apenas 0 ou 1, então deveria entrar como booleano para não confundir com valores inteiros.

In [6]:
print(df['frequenta_escola'].unique())
print(df['frequenta_escola'].dtype)

[0 1]
int64

### 3. Valores que parecem ser booleanos mas são categóricos
Temos um outro problema ainda com uma dessas colunas que é a coluna `crianca_matriculada_creche_pre_escola`, não é possível saber se `1`/`TRUE` ou `0`/`FALSE` é pré-escola ou creche, deveria ser categórico assim como as colunas `sexo` e `tipo`. Para resolver isso, podemos supor que `0`/`FALSE` é pré-escola e `1`/`TRUE` é creche.

In [7]:
print(df['crianca_matriculada_creche_pre_escola'].unique())

['0' '1' 'False' 'True']

In [8]:
# Exemplo de colunas do tipo categórico
print(df['tipo'].unique())
print(df['sexo'].unique())

['historico' 'rotineiro']
['male' 'female']

### 4. Textos em inglês
Acredito que para um melhor entendimento dos dados, eles precisam estar no mesmo idioma, então seria mais interessante mudar os valores e colunas que estão em inglês para o português, que é o idioma original da tabela. Então a coluna `updated_at` poderia se chamar `atualizado_em`, e os valores da coluna `sexo`, poderiam passar de `male`/`female` a `Masculino`/`Feminino`.

### 5. Padronizar os textos da coluna `tipo`

Os dados da coluna `tipo` podem ter apenas dois valores, `rotineiro` e `historico`, mas observando a tabela é possível ver que os outros dados seguem um padrão, que é começar por letra maiúscula e os acentos não são ignorados. Então para essa padronização podemos mudar os dados para `Rotineiro` e `Histórico`, respectivamente.

### 6. Listas que não estão no formato certo
Esse problema é referente às colunas `meios_transporte`, `doencas_condicoes`, `meios_comunicacao` e `em_caso_doenca_procura`, que são listas mas estão como strings pois algumas estão dentro de `'[]'`, mas outras não, então deveriam todas serem padronizadas como listas de strings.

In [9]:
df[['meios_transporte', 'doencas_condicoes', 'meios_comunicacao', 'em_caso_doenca_procura']].head(10)

,meios_transporte,doencas_condicoes,meios_comunicacao,em_caso_doenca_procura
0,Ônibus,"[""Outros""]","Internet, Televisão",Hospital Público
1,Ônibus,Hipertensão,"Internet, Televisão",[]
2,"Carro, Metrô, Ônibus, Trem",[],[],"Hospital Público, Unidade de Saúde"
3,"Carro, Ônibus","[""Outros""]","[""R\u00e1dio"", ""Televis\u00e3o"", ""Jornal"", ""In...",Hospital Público
4,"Metrô, Ônibus",[],"[""Televis\u00e3o"", ""Internet"", ""Jornal""]",[]
5,"[""Carro""]","Diabetes, Hipertensão",Televisão,"Hospital Público, Unidade de Saúde"
6,"Alternativo, Carro, Metrô, Ônibus, Outros, Trem","[""Diabetes""]","Internet, Televisão","Hospital Público, Rede Privada, Unidade de Saúde"
7,[],Diabetes,"Rádio, Televisão",Hospital Público
8,"Carro, Ônibus",[],"[""Televis\u00e3o"", ""Internet""]",Hospital Público
9,"Metrô, Ônibus, Trem",[],Internet,"[""Hospital P\u00fablico"", ""Unidade de Sa\u00fa..."

### 7. Vários encodings na mesma base de dados

Podemos ver nas colunas `meios_transporte`, `doencas_condicoes`, `meios_comunicacao` e `em_caso_doenca_procura` temos outro encoding que é o `windows-1252` e deve ser trocado para `utf-8` para a padronização.

In [12]:
df[['meios_transporte','doencas_condicoes', 'meios_comunicacao', 'em_caso_doenca_procura']].head()

,meios_transporte,doencas_condicoes,meios_comunicacao,em_caso_doenca_procura
0,Ônibus,"[""Outros""]","Internet, Televisão",Hospital Público
1,Ônibus,Hipertensão,"Internet, Televisão",[]
2,"Carro, Metrô, Ônibus, Trem",[],[],"Hospital Público, Unidade de Saúde"
3,"Carro, Ônibus","[""Outros""]","[""R\u00e1dio"", ""Televis\u00e3o"", ""Jornal"", ""In...",Hospital Público
4,"Metrô, Ônibus",[],"[""Televis\u00e3o"", ""Internet"", ""Jornal""]",[]

In [ ]:
# Função para encontrar caracteres no formato \uXXXX
def encontrar_caracteres_errados(string):
    return re.findall(r'\\u[0-9a-fA-F]{4}', string)

In [26]:
# Um dicionário para armazenar os caracteres codificados e uma string de exemplo para cada coluna
resultados_mt = {}
resultados_dc = {}
resultados_mc = {}
resultados_dp = {}

for index, row in df.iterrows():
    for erro in encontrar_caracteres_errados(row['meios_transporte']):
        if erro not in resultados_mt:
            resultados_mt[erro] = row['meios_transporte']

    for erro in encontrar_caracteres_errados(row['doencas_condicoes']):
        if erro not in resultados_dc:
            resultados_dc[erro] = row['doencas_condicoes']

    for erro in encontrar_caracteres_errados(row['meios_comunicacao']):
        if erro not in resultados_mc:
            resultados_mc[erro] = row['meios_comunicacao']

    for erro in encontrar_caracteres_errados(row['em_caso_doenca_procura']):
        if erro not in resultados_dp:
            resultados_dp[erro] = row['em_caso_doenca_procura']

In [27]:
# Vendo quais caracteres especiais existem em cada coluna
print('Coluna - \'meios_transporte\'')
for erro, string in resultados_mt.items():
    print(f"Caractere: {erro} - String: {string}")
print('\n')

print('Coluna - \'doencas_condicoes\'')
for erro, string in resultados_dc.items():
    print(f"Caractere: {erro} - String: {string}")
print('\n')

print('Coluna - \'meios_comunicacao\'')
for erro, string in resultados_mc.items():
    print(f"Caractere: {erro} - String: {string}")
print('\n')

print('Coluna - \'em_caso_doenca_procura\'')
for erro, string in resultados_dp.items():
    print(f"Caractere: {erro} - String: {string}")

Coluna - 'meios_transporte'
Caractere: \u00d4 - String: ["\u00d4nibus", "Alternativo"]
Caractere: \u00e3 - String: ["\u00d4nibus", "Caminh\u00e3o", "Metr\u00f4", "Trem"]
Caractere: \u00f4 - String: ["\u00d4nibus", "Caminh\u00e3o", "Metr\u00f4", "Trem"]
Caractere: \u00e7 - String: ["\u00d4nibus", "Carro\u00e7a", "Trem", "Metr\u00f4"]
Caractere: \u00ed - String: ["Mar\u00edtimo"]


Coluna - 'doencas_condicoes'
Caractere: \u00e3 - String: ["Hipertens\u00e3o"]
Caractere: \u00e1 - String: ["Sintom\u00e1tico Dermatol\u00f3gico"]
Caractere: \u00f3 - String: ["Sintom\u00e1tico Dermatol\u00f3gico"]
Caractere: \u00ed - String: ["Tuberculose", "Usu\u00e1rio de Drogas Il\u00edcitas"]
Caractere: \u00ea - String: ["Transtorno Mental", "Viol\u00eancia Dom\u00e9stica"]
Caractere: \u00e9 - String: ["Transtorno Mental", "Viol\u00eancia Dom\u00e9stica"]
Caractere: \u00e2 - String: ["C\u00e2ncer", "Hipertens\u00e3o"]


Coluna - 'meios_comunicacao'
Caractere: \u00e1 - String: ["R\u00e1dio", "Televis\u00e3o", "Jornal", "Internet"]
Caractere: \u00e3 - String: ["R\u00e1dio", "Televis\u00e3o", "Jornal", "Internet"]


Coluna - 'em_caso_doenca_procura'
Caractere: \u00fa - String: ["Hospital P\u00fablico", "Unidade de Sa\u00fade", "Farm\u00e1cia"]
Caractere: \u00e1 - String: ["Hospital P\u00fablico", "Unidade de Sa\u00fade", "Farm\u00e1cia"]
Caractere: \u00ed - String: ["Hospital P\u00fablico", "Unidade de Sa\u00fade", "Rede Privada", "Farm\u00e1cia", "Aux\u00edlio Espiritual", "Outros"]

### 8. Identidade de gênero
Além disso, aparentemente a coluna `identidade_genero` foi preenchida de maneira errônea, contendo valores como `Sim`, `Não` e valores referentes à orientação sexual como `Heterossexual` e `Homossexual`, esses valores não são conclusivos e não são o que a coluna pede, então devem ser trocados por algo como `Não informado` (assim como os valores nulos dessas colunas). Há também valores conclusivos mas que poderiam ser melhor explicados como `Cis` que poderia diferenciar entre mulher cis e homem cis, e `Travesti` que é um termo ofensivo para se referir à pessoas trans, então esses valores devem ser mudados com base na coluna `sexo`.

In [15]:
print(df['identidade_genero'].unique())

['Cis' 'Não' 'Outro' 'Homem transexual' 'Mulher transexual'
 'Heterossexual' 'Homossexual (gay / lésbica)' 'Bissexual' 'Sim'
 'Travesti' nan]

In [16]:
print(df['orientacao_sexual'].unique())

['Heterossexual' 'Homossexual (gay / lésbica)' 'Outro' 'Bissexual']

### 9. Float que deveriam ser int
Há dados em que não podem ser floats, eles sempre serão inteiros, como `pressao_sistolica` e `pressao_diastolica`, então devemos mudar o tipo destes dados para `int`.

In [17]:
df[['pressao_sistolica', 'pressao_diastolica']].dtypes

pressao_sistolica     float64
pressao_diastolica    float64
dtype: object

### 10. Valores nulos que não deveriam ser nulos
O último problema são os valores nulos nas colunas `altura`, `peso`, `pressao_sistolica`, `pressao_diastolica`. Que não é possível inferir, mas deveria ser obrigatório a informação desses dados pelo paciente, pois eles são importantes para um diagnóstico médico. Neste caso não é possível padronizar esses valores nulos, pois são valores numéricos e pessoais, seria possível inferir com base nos dados e tentar prever esses valores baseando-se em pessoas com características semelhantes, mas este não é o objetivo aqui.